import type { Metadata } from 'next'
import { Crimson_Pro, Inter } from 'next/font/google'
import Navigation from '@/components/navigation'
import AudioPlayer from '@/components/audio-player'
import { Toaster } from '@/components/ui/sonner'

import '../globals.css'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const crimson_pro = Crimson_Pro({
  variable: '--font-crimson-pro',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${crimson_pro.variable} antialiased`}
      >
        <Navigation />
        <AudioPlayer />
        {children}
        <Toaster />
      </body>
    </html>
  )
}
